//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GitMonitorEntities : DbContext
    {
        public GitMonitorEntities()
            : base(ConnectionBuilder.GetSqlConnection(), true)
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblRepo> tblRepoes { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
    }
}
