
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GitMonitor.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class tblBranch
{

    public long tblBranchID { get; set; }

    public string Name { get; set; }

    public long tblRepoID { get; set; }

    public bool EnableDeskTopNotifications { get; set; }

    public bool AutoPull { get; set; }

    public bool IsActive { get; set; }

    public bool HasUpstream { get; set; }

    public string Remote { get; set; }

    public string TrackingBranch { get; set; }

    public long AheadBy { get; set; }

    public long BehindBy { get; set; }



    public virtual tblRepo tblRepo { get; set; }

}

}
